image: <image name>
imageTag: master.1
imagePullSecret: dbase-gitlab-registry

env:
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: 1
  DB_HOST: postgresql
  DB_PORT: 5432
  DB_NAME: dbase

# This variables is taken from secret
# Value is secret name where variable value can be found
# Key in secret equals lowercased variable name with "_" replaced by "-"
# The secret should be created manually
envSecret:
  SECRET_KEY_BASE: sec_dbase
  DB_USER: sec_dbase
  DB_PASSWORD: sec_dbase

# Resources for app. Limits is the maximum number of resources that app cas use.
# And requests is resources that will be granted to the app at start time.
replicas: 2


resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  port: 80

ingress:
  host: mkube.com
  className: nginx
  path: /
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
